language: cpp

compiler:
  - g++

sudo: required

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - g++-4.8

script:
  - cd src
  - make lsm_tree_single_thread

notifications:
  email:
    on_success: always
    on_failure: never
    on_error: never
