dist: trusty

language: cpp

matrix:
  include:
    - os: linux

script:
  - g++ -std=c++11 -O3 test_data.cpp -o test_data
  - cd src && make -j8 lsmtree_with_queue

notifications:
  email:
    on_success: always
    on_failure: never
    on_error: never
