language: cpp

compiler:
  - gcc

os:
  - linux

sudo: required

branches:
  - master

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
       export CC="gcc-4.8";
       export CXX="g++-4.8";
    fi

script:
  - cd src
  - make all

notifications:
  email:
    on_success: always
    on_failure: never